version: '3'
services:
  db:
    restart: always
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - '/data/db:/data/db' 
    command: 'mongod'
    
  server:
    container_name: server
    image: server:latest
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    restart: 'on-failure'
    stdin_open: true
    links:
      - db
    depends_on:
      - db

  bot:
    container_name: bot
    image: bot:latest
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: 'on-failure'
    stdin_open: true
    links:
      - server
    depends_on:
      - server

  web:
    image: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/cloud.homeofcode.com/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/cloud.homeofcode.com/privkey.pem:/etc/nginx/privkey.pem
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    restart: 'on-failure'
    depends_on:
      - server